name: Build CV PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Verify LaTeX preamble
      run: |  
        test -f mysetup.tex || (echo "ERROR: MySetup.tex missing" && exit 1)

    - name: Verify LaTeX vars
      run: |  
        test -f vars.tex || (echo "ERROR: vars.tex missing" && exit 1)

    - name: Verify LaTeX cv
      run: |  
        test -f cv.tex || (echo "ERROR: cv.tex missing" && exit 1)

    - name: Verify Makefile
      run: |  
        test -f makefile || (echo "ERROR: makefile missing" && exit 1)

    - name: Build CV with latexmk
      run: |
        make all

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: CV-pdf
        path: cv.pdf

  deploy_to_pages:
    name: Deploy to github pages
    needs: build-pdf
    runs-on: ubuntu-latest

    steps:
    - name: Download pdf
      uses: actions/download-artifact@v4
      with:
        name: cv-pdf

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        working-directory: ./